### ISSUE TITLE
Change Status Bar color for all activities

### ISSUE THREAD

**Issue by fin1te** [DSC-PHCET/gdsc-android-app#1]
Currently, all Fragments and Activities have the default blue status bar, change it to a colour more suitable with the app's user interface (preferably some shade of grey) as well as figure out how to change the icon colour to a dark shade.

**NOTE:** 
- Needs to be Implemented in all activities.
- If you want to try to solve this issue, leave a comment asking me to assign you this issue and I'll assign it to you, once you've been assigned, you can start working on the Implementation.

**Comment by sakshii-25** [comment]
I want to work on this issue, it would be great if you could assign it to me.

**Comment by fin1te** [comment]
@sakshii-25 assigned this issue to you, good luck!

**Comment by Pranjali-49** [comment]
Hey @fin1te, I would like to work on this issue under GSSOC'22!

**Comment by fin1te** [comment]
> Hey @fin1te, I would like to work on this issue under GSSOC'22!

Hey @Pranjali-49, GSSoC'22 contributing period starts from 1st March, please comment back on/or after 1st March and I'll assign you the issue.

**Comment by Pranjali-49** [comment]
Okay! Thank you for replying.

**Comment by sdcode001** [comment]
hello @fin1te, I want to solve this issue under GSSoC,22. can you please assign me this issue

**Comment by Pranjali-49** [comment]
Hey @fin1te can you please assign this issue to me now since the contributing period has started.

**Comment by fin1te** [comment]
> Hey @fin1te can you please assign this issue to me now since the contributing period has started.

Sure, try it out. for any queries message us on Discord.

**Comment by fin1te** [comment]
@Pranjali-49 let me know the tentative timeline under which you'll be submitting the PR.

**Comment by fin1te** [comment]
> hello @fin1te, I want to solve this issue under GSSoC,22. can you please assign me this issue

@sdcode001 You can take up this issue if it's not solved by the current assignee under the tentative timeline

**Comment by sdcode001** [comment]
@fin1te okay

**Comment by sdcode001** [comment]
@fin1te is there any other issue in this project??

**Comment by fin1te** [comment]
> @fin1te is there any other issue in this project??

added a few just now, will be creating more issues by EoD today or tomorrow.

**Comment by sdcode001** [comment]
@fin1te ok thanks

**Comment by fin1te** [comment]
@Pranjali-49 Make sure you make all the changes on a new branch, don't make a PR on the master branch as it is the Production branch.

**Comment by Pranjali-49** [comment]
> > Hey @fin1te can you please assign this issue to me now since the contributing period has started.
> 
> Sure, try it out. for any queries message us on Discord.

Okay. Thank you!

**Comment by Pranjali-49** [comment]
> @Pranjali-49 let me know the tentative timeline under which you'll be submitting the PR.

I will submit it before 5th of March.

**Comment by Pranjali-49** [comment]
> @Pranjali-49 Make sure you make all the changes on a new branch, don't make a PR on the master branch as it is the Production branch.

Noted.

**Comment by fin1te** [comment]
> > @Pranjali-49 let me know the tentative timeline under which you'll be submitting the PR.
> 
> I will submit it before 5th of March.

Good luck! :D
