### ISSUE TITLE
[Bug]: Cards in the "Team" Section should be of same size, to make it more visually appealing

### ISSUE THREAD

**Issue by its-me-debk007** [DSC-PHCET/gdsc-android-app#13]
### Contact Details

debashish.joy@gmail.com 

### What happened?

Cards of full width feel more visually appealing to the eyes

![msg876029335-6137](https://user-images.githubusercontent.com/81604986/156907214-697434c2-7be5-455d-b5d4-3be7d02d4bc1.jpg)

![msg876029335-6136](https://user-images.githubusercontent.com/81604986/156907221-8d4b8705-ed0b-41d2-8248-f30058138693.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by its-me-debk007** [comment]
Please assign this issue to me under GSSOC. I'll be glad to work on this issue and help improve the app using my insights as well.

**Comment by barkatul** [comment]
I want to work on this issue. Can you please assign this to me

**Comment by fin1te** [comment]
Go ahead @its-me-debk007, update your fork with the latest commits of this upstream before you start working on this issue to make sure your PR has all the recent commits covered, for any issues ping me on discord.

**Comment by fin1te** [comment]
Resolved this issue in PR #23

**Comment by its-me-debk007** [comment]
Thanx @fin1te !!
