### ISSUE TITLE
Feature: Tab layout instead of Bottom Navigation view, for smooth transition among pages

### ISSUE THREAD

**Issue by its-me-debk007** [DSC-PHCET/gdsc-android-app#14]
### Feature description

I've implemented tab layout in such a way, such that it retains the look of Bottom Navigation View and has the features of TabLayout at the same time. The implementation video is attached below.

https://user-images.githubusercontent.com/81604986/156909937-001d958b-e17c-4b11-8451-6060c3b2aa0a.mp4

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by its-me-debk007** [comment]
Please assign this issue to me under GSSOC. I really want to work on this one.

**Comment by SB2318** [comment]
@its-me-debk007 It would be nice if you could use the tab layout.
If you design according to your video, then it will little bit hard for the user to understand the structure. You can share something else about it in the respective channel.

**Comment by SB2318** [comment]
If your idea is acceptable, you will be assigned.

**Comment by its-me-debk007** [comment]
Ok! Thinking of an improved layout.

**Comment by fin1te** [comment]
Hey, TabLayout isn't necessary and as of now, bottomNav is just fine, hence closing this issue.

Create a new issue if you get any other ideas. :D
