### ISSUE TITLE
  Modify the past event part of the GDSC fragment using RecyclerView.

### ISSUE THREAD

**Issue by SB2318** [DSC-PHCET/gdsc-android-app#16]
### Feature description

![pastEvent](https://user-images.githubusercontent.com/87614560/156920169-e4595db6-2b7e-48fb-8ac0-6a76f6ccfe6a.png)

Currently, the past event view has been done with the help of LinearLayout. All you have to do is display all the data with **Recycler View** and **Horizontal LayoutManager.**

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by priyanshuborole** [comment]
Can i work in this @SB2318?

**Comment by SB2318** [comment]
Sure, go ahead.

**Comment by AgarwalsRahul** [comment]
I would like to work on this issue

**Comment by fin1te** [comment]
@priyanshuborole please ping me on discord so that I can explain to you in detail what needs to be done so that you can start working on it, and I'll assign you the issue.

**Comment by AyushGupta649** [comment]
Can u assign me this task

**Comment by fin1te** [comment]
> Can u assign me this task

It's already assigned to 1 participant, if he's not able to do it then I'll assign you, meanwhile lookout for newer issues that I'll be adding today
