### ISSUE TITLE
Make all "Tracks" clickable in AboutFragment.

### ISSUE THREAD

**Issue by SB2318** [DSC-PHCET/gdsc-android-app#17]
### Feature Description

![much_more](https://user-images.githubusercontent.com/87614560/156921311-1246af3f-0926-4daa-9eb8-63e24360acbb.png)

When the user clicks on any of the tracks, he should be redirected to a new Fragment (`TrackDetailFragment`), and this fragment will contain data related to that track.

*NOTE :*
- Clicking on any track should redirect to `TrackDetailFragment` only, all tracks should not have a separate Fragment.
- You can pass a string argument in NavDirection so that when we reach `TrackDetailFragment`, we know that which track we came from, and can populate the `TrackDetailFragment` accordingly.

For any queries/doubts related to this or any other issue on this project, ping @fin1te on Discord.

**Comment by priyanshuborole** [comment]
Can i work on this? @SB2318

**Comment by Vibhuti2002** [comment]
can i work on this? @SB2318

**Comment by SB2318** [comment]
> can i work on this? @SB2318

Go ahead.

**Comment by AgarwalsRahul** [comment]
I would like to work on this issue

**Comment by Vibhuti2002** [comment]
ok sure @SB2318

**Comment by fin1te** [comment]
Updated the description and title of this issue, you can start working on this now @Vibhuti2002.

Delete your current fork and commit and start fresh again, for any queries ping us on discord.

**Comment by Vibhuti2002** [comment]
Okay @fin1te
