### ISSUE TITLE
Modify the upcoming event part.

### ISSUE THREAD

**Issue by SB2318** [DSC-PHCET/gdsc-android-app#18]
### Feature description

![searching_lottie](https://user-images.githubusercontent.com/87614560/156922074-6cdfc49c-af7f-48a4-bf03-a704380a8525.png)

This searching lottie animation and the message is visible only when there are no upcoming events.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by MohitGupta121** [comment]
I want to work on this @SB2318 or @fin1te can you please assign it to me.

**Comment by SB2318** [comment]
Okay, go ahead

**Comment by MohitGupta121** [comment]
> Okay, go ahead

Okay Thanks you
There is no need of assign???

**Comment by fin1te** [comment]
> > Okay, go ahead
> 
> Okay Thanks you There is no need of assign???

I will ping you on discord, need to have a conversation and explain you what needs to be exactly done before assigning the issue.

**Comment by MohitGupta121** [comment]
> > > Okay, go ahead
> > 
> > 
> > Okay Thanks you There is no need of assign???
> 
> I will ping you on discord, need to have a conversation and explain you what needs to be exactly done before assigning the issue.

Okay, sure that's great but I understand the issue 
But for more clear ping on discord.

**Comment by fin1te** [comment]
Closing the issue for now as discussed with you on discord, will re-open after #16 is completely implemented.
