### ISSUE TITLE
#1 Link the Tracks in About-us Fragments with relevant Google Search results

### ISSUE THREAD

**Issue by fin1te** [DSC-PHCET/gdsc-android-app#2]
In the about us screen, there are different tracks (domains we cover at GDSC PHCET), when a user clicks on any track, he should be redirected to a google search of that track.

Example : 
User clicks on "App Development", then he should be redirected to a Google search result of "App Development"

For any doubts/clarifications comment here or discuss with us on Discord.

**Comment by mayanksony** [comment]
hi can i contribute to this issue under GSSOC'22

**Comment by sakshi0210** [comment]
Hello @fin1te 
Can you please assign this topic to me ?, I will try my best to get the task done.
Thanks!!

**Comment by sdcode001** [comment]
hey, @fin1te i want to work on this issue. please assign it to me

**Comment by fin1te** [comment]
Hey @mayanksony and @sakshi0210, 
I'll be assigning this one to both of you, @mayanksony solve this issue only for the first 3 tracks (App Development, Machine Learning and Web Development)

@sakshi0210 comment [on this issue](https://github.com/DSC-PHCET/gdsc-android-app/issues/6) and I will assign this to you, similarly, just solve this issue only for the last 3 tracks (Google Cloud, Open Source, + Much More)

**Comment by fin1te** [comment]
@mayanksony  Make sure you make all the changes on a new branch, don't make a PR on the master branch as it is the Production branch.

**Comment by fin1te** [comment]
@mayanksony any updates? please update us if you're solving this or will be giving the chance to someone else.

**Comment by mayanksony** [comment]
@fin1te I am done with it would make a PR soon

**Comment by fin1te** [comment]
> @fin1te I am done with it would make a PR soon

@mayanksony alright sure

**Comment by SB2318** [comment]
@mayanksony any update

**Comment by fin1te** [comment]
Closing this issue as the PR linked was many commits behind the current project, and the same issue has been assigned to another participant as all the tracks need to be redirected to the same fragment, check #17 for more info.
