### ISSUE TITLE
Feature: Implement UpcomingEvents RecyclerView in HomeFragment

### ISSUE THREAD

**Issue by fin1te** [DSC-PHCET/gdsc-android-app#25]
### Feature description

UpcomingEvents RecyclerView needs to be implemented similar to the PastEvents RecyclerView in the HomeFragment, refer to that code, I have posted the Firebase RTDB Schema on Discord, for any clarification, ping me on Discord. (@fin1te)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by MohitGupta121** [comment]
I want to work on this please assign me

**Comment by fin1te** [comment]
> I want to work on this please assign me

Good luck!

**Comment by fin1te** [comment]
Closing this Issue as it has been solved in PR #27
