### ISSUE TITLE
Remove the TrackDetailFragment and replace its implementation with TrackDetailActivity

### ISSUE THREAD

**Issue by fin1te** [DSC-PHCET/gdsc-android-app#26]
### Feature description

Remove the `TrackDetailFragment` and it's XML and replace it's implementation with a new `TrackDetailActivity` (Similar to the `EventDetailActivity` in `HomeFragment`)

For any clarification ping me on Discord @fin1te 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by Vibhuti2002** [comment]
Could you please assign it to me?

**Comment by fin1te** [comment]
Good luck!
