### ISSUE TITLE
UI Design : Design a UI Template for TrackDetailActivity and set up the activity properly for work

### ISSUE THREAD

**Issue by SB2318** [DSC-PHCET/gdsc-android-app#29]
### Feature description

- Design a UI Design template for TrackDetailActivity, this UI design should consist of what all things would be there in TrackDetailActivity for any given track.

- Keep the design minimal (you can take a look at UI designs from dribbble / figma boards for inspiration / ideas.

**Comment by fin1te** [comment]
Hey @SB2318, I have updated this issue and the description, take a look and If you're interested to work on it, you can assign this issue to yourself :D

**Comment by SB2318** [comment]
@fin1te I have a plan for it. I want to discuss about this before starting work. So, please give me a time.😇

**Comment by fin1te** [comment]
> @fin1te I have a plan for it. I want to discuss about this before starting work. So, please give me a time.😇

alright sure :D ping me on discord whenever you want to ask/show anything!

**Comment by fin1te** [comment]
assigning this to you

**Comment by SB2318** [comment]
> > @fin1te I have a plan for it. I want to discuss about this before starting work. So, please give me a time.😇
> 
> alright sure :D ping me on discord whenever you want to ask/show anything!

Okay
