### ISSUE TITLE
Feature: Make Splash Screen for this App 

### ISSUE THREAD

**Issue by maityamit** [DSC-PHCET/gdsc-android-app#30]
### Feature description

# Make Splash Screen for this App 

## Figma Design
![Frame 1 (3)](https://user-images.githubusercontent.com/74618071/157686593-db991c5e-2e35-420e-bf19-3fe26ff60519.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by fin1te** [comment]
@maityamit would you like to work on this issue?

**Comment by maityamit** [comment]
@fin1te 
Yes , Please assign me

**Comment by fin1te** [comment]
> @fin1te Yes, Please assign me

Good luck! don't use a fragment/activity to implement the Splash, you can implement splash natively in Android, use that method.

**Comment by fin1te** [comment]
Also, there are some design changes, use `Google Developer Student Club` instead of `Developer Student Clubs`

and the logo design is different, refer this image for the logo : https://media.discordapp.net/attachments/735859351998169088/951123395481854042/ic_gdsc.PNG

**Comment by maityamit** [comment]
> Also, there are some design changes, use `Google Developer Student Club` instead of `Developer Student Clubs`
> 
> and the logo design is different, refer this image for the logo : https://media.discordapp.net/attachments/735859351998169088/951123395481854042/ic_gdsc.PNG

Ok 👌

**Comment by fin1te** [comment]
you can also refer this if needed for splash screen implementation example : https://www.mongodb.com/developer/how-to/splash-screen-android/

**Comment by Satya-Prakash0** [comment]
Can you assign me this issue I would like to work on this

**Comment by SB2318** [comment]
I think this feature is needed. So, I am Reopening the issue. Thanks, @maityamit for giving some time on creating such an issue.
But at this moment I am unassigning you because it will depend on you, whether you are willing to work on this issue or not.

**Comment by maityamit** [comment]
@SB2318 Yups , I want to work at this issue 
Please assign me

**Comment by SB2318** [comment]
Okay, But discuss with @fin1te about your work.

**Comment by fin1te** [comment]
Hey, after careful consideration I don't think we need to have the splash screen right now, as we have implemented the shimmer effect for now in the `HomeFragment`, so for now that is fine, if later on, we have to remove shimmer / have some other functionalities in the `HomeFragment` that requires API Calls / Background loading then we can have a splash screen which will cover for the time we get API response in.

Thanks, @maityamit for raising this issue earlier and @SB2318 for your help on the issues :D

We can re-open this issue later on if we ever have more complex implementations in the `HomeFragment`, hence closing this issue for now.
