### ISSUE TITLE
Add Contribution badges in the Readme file of this Project.

### ISSUE THREAD

**Issue by priyanshuborole** [DSC-PHCET/gdsc-android-app#32]
### Description

Add Contribution badges in the Readme file of this Project.

Refer to [this](https://github.com/kunal-kushwaha/DSA-Bootcamp-Java/blob/main/README.md#thanks-to-all-the-contributors-%EF%B8%8F) repository for a sample readme file with Contribution badges.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by lalit-patel** [comment]
I want to work on this issue

**Comment by SB2318** [comment]
@priyanshuborole would you like to work on this issue?

**Comment by priyanshuborole** [comment]
@SB2318 You can assign him @lalit-patel .  He wants to start with opensource so this issue will be a good first issue for him

**Comment by SB2318** [comment]
Okay 👍
