### ISSUE TITLE
Feature: There will be a Floating or normal Share button where user can share any event via any app (Using Intent) 

### ISSUE THREAD

**Issue by maityamit** [DSC-PHCET/gdsc-android-app#33]
## There will be a Floating Share button where user can share any event via any app (Using Intent) 

<img src="https://user-images.githubusercontent.com/74618071/157913324-81dd1f7b-28bf-419e-b72c-be0446490e66.jpg" width="20%">

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by maityamit** [comment]
### I would like to work this feature under GSSoC'22 .

**Comment by SB2318** [comment]
@maityamit This is good idea, but You do it with something else, not with floating action button. like toolbar or something else. Think about it.

**Comment by maityamit** [comment]
@SB2318 Ohk , Have you any idea about this , where I would place ?

**Comment by SB2318** [comment]
I will contact you on discord.

**Comment by fin1te** [comment]
hey @maityamit let's connect on discord tomorrow or day after regarding this issue?

**Comment by maityamit** [comment]
@fin1te yups tommorow
