### ISSUE TITLE
[Bug]: event details poster image gets cropped from top and bottom

### ISSUE THREAD

**Issue by Vibhuti2002** [DSC-PHCET/gdsc-android-app#35]
### Contact Details

vibhuti2002patil@gmail.com

### What happened?

![Screenshot (281)](https://user-images.githubusercontent.com/86654213/158011162-7ab4c784-7aa8-469a-9cf5-c26cbe074331.png)
![Screenshot (280)](https://user-images.githubusercontent.com/86654213/158011177-eb5f325e-0710-4e04-af33-f8031155b65f.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Vibhuti2002** [comment]
i want to work on this issue

**Comment by SB2318** [comment]
You mean you want to fit the image with in the place right? Please confirm

**Comment by fin1te** [comment]
> You mean you want to fit the image with in the place right? Please confirm

Yes I believe

**Comment by fin1te** [comment]
@Vibhuti2002 hadn't realised this was an issue occurring in other screen sizes, go ahead and thanks for pointing this out!

**Comment by SB2318** [comment]
> > You mean you want to fit the image with in the place right? Please confirm
> 
> Yes I believe

😇

**Comment by Vibhuti2002** [comment]
> You mean you want to fit the image with in the place right? Please confirm

yes
