### ISSUE TITLE
Feature: Update TeamFragment with new details

### ISSUE THREAD

**Issue by fin1te** [DSC-PHCET/gdsc-android-app#36]
### Feature description

Add Images of all existing team members, and add 8 more new team members at the end in the same order.

Necessary details will be shared with the assignee via Discord.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by priyanshuborole** [comment]
Can I work on this issue?

**Comment by fin1te** [comment]
> Can I work on this issue?

Good luck!
