### ISSUE TITLE
Feature: Custom Loading dialog in HomeFragment while data gets fetched

### ISSUE THREAD

**Issue by fin1te** [DSC-PHCET/gdsc-android-app#39]
### Feature description

Need to implement a custom dialog in HomeFragment which will be visible till the data is fetched from the Firebase.

Use Google's LottieAnimation as the view for the Dialog (as in AboutFragment).

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by MohitGupta121** [comment]
I want to work on this please assign me
