### ISSUE TITLE
Feature: Implement Loading Shimmer for EventDetailActivity

### ISSUE THREAD

**Issue by fin1te** [DSC-PHCET/gdsc-android-app#45]
### Feature description

Add Shimmer effect for the EventDetailActivity similarly as implemented in HomeFragment, for any clarification message on discord.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by MohitGupta121** [comment]
@fin1te can you please review the PR for this issue #47
