### ISSUE TITLE
Feature: Add a no Internet connection Animation

### ISSUE THREAD

**Issue by maroof31** [DSC-PHCET/gdsc-android-app#48]
### Feature description

When user clicks in upcoming event or past event it shows empty event detail activity with failed toast
we can show some no internet connection lottie animation.
![e583f960-7ce0-47d3-9c0c-04593226f4fe](https://user-images.githubusercontent.com/89301157/159106277-c3dd84f2-fde7-42eb-8c3d-9040677ceb2f.jpg)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by SB2318** [comment]
@fin1te please check the issue.

**Comment by fin1te** [comment]
This feature isn't needed like this, rather what we can do is create a snackbar whenever the internet is gone.

**Comment by maroof31** [comment]
Can I create the snackbar.

**Comment by maroof31** [comment]
@fin1te

**Comment by SB2318** [comment]
@finite

His idea needs a little modification.
But before, you see the problem in this video when our phone is not connected to the internet.  Please guide him.

https://user-images.githubusercontent.com/87614560/159209410-74d8b470-ea09-4e2f-9d37-0e8407fa6ea0.mp4

It's better to aware the user about the problem with a message.

**Comment by fin1te** [comment]
> @finite
> 
> His idea needs a little modification. But before, you see the problem in this video when our phone is not connected to the internet. Please guide him.
> 
>  snackbar.mp4 
> It's better to aware the user about the problem with a message.

Hey, sure! :D

**Comment by fin1te** [comment]
![image](https://user-images.githubusercontent.com/62439440/160221919-5a5d3ec4-a79e-48b7-b09a-63037cffa104.png)

@maroof31 please take a look at this implementation of the `no internet connection` feature implemented using snackbar.
Please leave a comment if you're going to try this out.

NOTE : make sure you update your clone of this repo before you start working, to make sure your origin is updated with this upstream.

**Comment by fin1te** [comment]
@maroof31 let me know if you have any doubts / queries.

**Comment by maroof31** [comment]
@fin1te sure please assign it to me.

**Comment by fin1te** [comment]
> @fin1te sure please assign it to me.

done, good luck!

**Comment by fin1te** [comment]
@maroof31 hey any updates? please revert back if you've worked on this issue.

**Comment by maroof31** [comment]
@fin1te sorry for being late. I am working on it.

**Comment by fin1te** [comment]
@maroof31 alright, please let us know by when will it be done.
