### ISSUE TITLE
[Bug]: After the date is over,  move the upcoming event into past event part.

### ISSUE THREAD

**Issue by SB2318** [DSC-PHCET/gdsc-android-app#49]
### Contact Details

susmitabhattacharya2023@gmail.com

### What happened?

A bug happened!
![upcoming_event](https://user-images.githubusercontent.com/87614560/159109424-26818674-b312-40e0-95a6-b2dc56897cc6.png)

**As we see here, Even after the date has passed, it is still showing at the upcoming event part.** Let's try to fix it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sdcode001** [comment]
@SB2318 i want to work on this issue. please assign it to me under GSSoc'22

**Comment by SB2318** [comment]
Okay @sdcode001, contact us on discord before you start the work.

**Comment by sdcode001** [comment]
thank you

**Comment by fin1te** [comment]
@sdcode001 hey, your fork of the upstream is 17 commits behind, please update your fork and let me know if you're still working on this issue.

**Comment by fin1te** [comment]
unassigned due to inactivity of the issue, @sdcode001 let me know if you want to work on this issue, we'll assign you.

**Comment by Hend123** [comment]
please,
in upcoming event session 2 and in past seesion 1
then there is no bug @SB2318

**Comment by SB2318** [comment]
@Hend123 sorry, I can't understand what you are trying to say.

**Comment by Hend123** [comment]
![ddd](https://user-images.githubusercontent.com/31670657/160872806-ac1a4a34-e867-4706-b919-2d4e292424bb.jpg)

flutter festival session 1 in past events is not flutter festival session 2 in upcoming events.
then after the date has passed, it is not still showing at the upcoming event part


@SB2318

**Comment by SB2318** [comment]
Check the date, March 15 . Now it is March 29, date is over, it means this is a past event , right.
We want a functionality that will check the date also, and remove the events from upcoming events database accordingly

**Comment by sdcode001** [comment]
@SB2318 I want to work on this issue. please assign it to me.

**Comment by SB2318** [comment]
@sdcode001 how much time will you take to complete it?  Don't worry, give an approximate time limit.

**Comment by sdcode001** [comment]
8-10 days

**Comment by SB2318** [comment]
Minimize it to 7 days. Come into discord server, we will help you.

**Comment by sdcode001** [comment]
ok I'll try....assign me

**Comment by MohitGupta121** [comment]
@SB2318 I want to work on this issue also if no one is working, as I know the logic behind this.

**Comment by SB2318** [comment]
Okay, If you face any difficulty contact us on discord.😇 And already you have taken one issue. So I am giving you 8 days time to complete it.

**Comment by MohitGupta121** [comment]
> Okay, If you face any difficulty contact us on discord.😇 And already you have taken one issue. So I am giving you 8 days time to complete it.

Okay thanks you

**Comment by fin1te** [comment]
closing this issue for now as we'll need a premium firebase account to use the cloud functions, hence this functionality isn't possible to do right now, closing this for now till we figure out a better way to approach this issue.
