### ISSUE TITLE
[Bug]: Make all the upcoming events visible in the upcoming event part.

### ISSUE THREAD

**Issue by SB2318** [DSC-PHCET/gdsc-android-app#50]
### Contact Details

susmitabhattacharya2023@gmail.com

### There are currently many upcoming events. 

![upcoming_web_event](https://user-images.githubusercontent.com/87614560/159109747-bcb4e2de-cb97-4979-b7ad-2c8118cdb338.png)

### But all are not showing properly.
![upcoming_event](https://user-images.githubusercontent.com/87614560/159109772-503e34b3-954b-4714-b841-2746a14eeca8.png)

 We can provide this feature in the application.
 If  anyone want to work on the issue, contact us on discord.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fin1te** [comment]
Those upcoming events are from all the GDSCs around the globe, in the app currently we only have to show the upcoming events of GDSC PHCET so this isn't a bug, hence closing this issue

**Comment by SB2318** [comment]
Okay
