### ISSUE TITLE
Feature: Notify the user whenever there are any new upcoming events.

### ISSUE THREAD

**Issue by SB2318** [DSC-PHCET/gdsc-android-app#51]
### Feature description

You need to show a notification to the user whenever new upcoming event is added. 
Notification message something like this..
"New event is coming...Check it out.." or something else.

Prerequisite knowledge: LiveData

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by fin1te** [comment]
Whoever wants to work on this issue lets first have a discussion on how you're going to implement it, once we come to a conclusion/fixed solution of it then you can start working on this issue, and based on the methodology we'll assign the level.

**Comment by priyanshuborole** [comment]
can I work on this issue?

**Comment by fin1te** [comment]
> can I work on this issue?

done, good luck!

**Comment by MohitGupta121** [comment]
I want to work on this issue if @priyanshuborole have any problem?

**Comment by priyanshuborole** [comment]
Okay @MohitGupta121 You can 👍

**Comment by SB2318** [comment]
@priyanshuborole don't be disappointed , new issues will come.Keep yourself updated with this project. 😇

**Comment by SB2318** [comment]
Sorry @MohitGupta121😅

**Comment by MohitGupta121** [comment]
> Sorry @MohitGupta121😅

What? Np problem it's ok😅

**Comment by fin1te** [comment]
@MohitGupta121 good luck!

**Comment by MohitGupta121** [comment]
@fin1te can I use Cloud Function to automate the notification
