### ISSUE TITLE
Feature: Show a progress bar at the time of verification of the certificate.

### ISSUE THREAD

**Issue by SB2318** [DSC-PHCET/gdsc-android-app#53]
### Feature description

At present it looks like this.

![certificate2](https://user-images.githubusercontent.com/87614560/159210413-ef5ed3c8-8433-4f9d-a015-3f16ac844d9a.png)

But, here we can show a progress bar when the user clicks on the verify button. Also, change the toast message with an appropriate message, in case any failure occurs.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by sdcode001** [comment]
@SB2318 i want to work on this issue. please assign it to me

**Comment by sdcode001** [comment]
@fin1te next time i'll make the PR on this issue with the appropriate solution. Can you please reassign to me.
