### ISSUE TITLE
Feature: Show a confirmation dialogue when the certificate verification is successful

### ISSUE THREAD

**Issue by SB2318** [DSC-PHCET/gdsc-android-app#54]
### Design
---

![confirmation (3)](https://user-images.githubusercontent.com/87614560/159413058-4e726e9d-9aff-495a-aba1-7931da37104e.jpg)

**Message : "Verification successful"**

**setCancellable: true**

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by Vrushali-anil-Chaudhari** [comment]
I would like to contribute to this issue.

**Comment by Vrushali-anil-Chaudhari** [comment]
Thank you

**Comment by SB2318** [comment]
Go ahead. If you face any difficulty connect with us on the respective channel.😇

**Comment by SB2318** [comment]
@Vrushali-anil-Chaudhari please wait for sometime. Once @fin1te check PR #56 and merge it or make a decision, then you have to update your repo and start work.

**Comment by fin1te** [comment]
Hey @Vrushali-anil-Chaudhari, go ahead and try it out, please reply here if you're going to try solving this issue.

**Comment by Vrushali-anil-Chaudhari** [comment]
YESS!!Sorry for the delay i will update soon by tomorrow

**Comment by Vrushali-anil-Chaudhari** [comment]
Thank you!
