### ISSUE TITLE
Feature: Add a "learn more" button in the description cardview of About Us Fragment. 

### ISSUE THREAD

**Issue by SB2318** [DSC-PHCET/gdsc-android-app#55]
### Feature description

![Screenshot_20220323-191619~2](https://user-images.githubusercontent.com/87614560/159715861-aaae5905-f302-4c9a-ba0a-a84388bb257d.png)
Below the description (inside the CardView) you have to add the button.

Design: 
![Screenshot_20220323-191538~2](https://user-images.githubusercontent.com/87614560/159716115-11b224f0-8b4a-4cb7-b267-d6cf84167bc9.png)

Contact us on discord for more information.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by SB2318** [comment]
Don't worry. This is easy issue, I will share my plan on the respective channel to the assignee.

**Comment by sdcode001** [comment]
@SB2318 i want to work on this issue. please assign it to me

**Comment by fin1te** [comment]
> @SB2318 i want to work on this issue. please assign it to me

hey, please check out the previous issue you had been assigned, and let us know which issue you want to work on :D will assign you that issue accordingly.

**Comment by Vibhuti2002** [comment]
can i work on this issue?

**Comment by SB2318** [comment]
Okay, connect with me on discord, before you start the work.
