### ISSUE TITLE
#2 Link the Tracks in About-us Fragments with relevant Google Search results

### ISSUE THREAD

**Issue by fin1te** [DSC-PHCET/gdsc-android-app#6]
In the about us screen, there are different tracks (domains we cover at GDSC PHCET), when a user clicks on any track, he should be redirected to a google search of that track.

Example :
User clicks on "App Development", then he should be redirected to a Google search result of "App Development"

For any doubts/clarifications comment here or discuss with us on Discord.

**Comment by sdcode001** [comment]
hey, @fin1te i want to work on this issue under GSSoC'22. please assign it to me

**Comment by fin1te** [comment]
> hey, @fin1te I want to work on this issue under GSSoC'22. please assign it to me

This one is already given to another contributor, If they don't take it in a couple of hours I'll assign it to you, meanwhile feel free to take a look at the other issues, and I'll be adding more issues in a while.

Ping me on Discord if you have any queries, thanks!

**Comment by sakshi0210** [comment]
Hello @fin1te
Can I start working to solve this issue only for the last 3 tracks (Google Cloud, Open Source+ Much More)

**Comment by fin1te** [comment]
@sakshi0210 good luck! 

for the 'Much More' track, it should redirect to `https://gdsc.community.dev/pillai-hoc-college-of-engineering-and-technology-navi-mumbai/`

**Comment by fin1te** [comment]
@sakshi0210  Make sure you make all the changes on a new branch, don't make a PR on the master branch as it is the Production branch.

**Comment by sakshi0210** [comment]
Ok I will make changes at the new branch.

**Comment by maityamit** [comment]
@fin1te 
# this is right way na ? to create in a new branch

In the project directory
☑️  Checkout to a new branch
``` git checkout -b my-branch ```
☑️  Make required changes to code. After making the changes, stage the changes, make a commit and push the code:
stage the changes
``` git add . ```
commit the changes
``` git commit -m "commit message" ```
push the changes
``` git push origin my-branch ```


☑️ Then create a PR.

**Comment by fin1te** [comment]
> After making the changes, stage the changes, make a commit and push the code

yes

**Comment by fin1te** [comment]
A similar issue was just resolved by another participant which solves this issue as well, hence closing this issue, will be adding more issues by tomorrow.
