### ISSUE TITLE
Feature: Remove the App Development Track. 

### ISSUE THREAD

**Issue by SB2318** [DSC-PHCET/gdsc-android-app#63]
### Feature description

Remove the app development track and replace it with  **1. Android Development 2. Flutter Development** 
Design will be the same. You  have to add two CardView (after removing the previous) with appropriate Images and text. 

![app_dev](https://user-images.githubusercontent.com/87614560/161498430-51a1f60f-40a4-4346-b40a-a5128bdc2e11.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by sdcode001** [comment]
@SB2318  I think now I'm not that much ready to solve issue #49. So can you please give me this issue to work with in replace of issue #49

**Comment by SB2318** [comment]
As you wish.😇

**Comment by sdcode001** [comment]
Thanks
