### ISSUE TITLE
Feature: Add  some more tracks.

### ISSUE THREAD

**Issue by SB2318** [DSC-PHCET/gdsc-android-app#64]
### Feature description

Guys this issue is little bit interesting.
You have to add some more tracks (some more CardView) with relevant Images and text. 
![app_dev](https://user-images.githubusercontent.com/87614560/161499678-a0f6616c-3424-4b51-b2ce-d100c7453707.png)

### **Tracks name:**

1. Cloud
2. AR/VR
3. Graphic Design

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by MohitGupta121** [comment]
I want to work on this issue @fin1te @SB2318 please assign me.

**Comment by SB2318** [comment]
Okay, go ahead.

**Comment by MohitGupta121** [comment]
Okay Thanks you

**Comment by MohitGupta121** [comment]
@fin1te @SB2318 can you please review my PR #65 for this issue
