### ISSUE TITLE
Feature: Enable action bar for TrackDetailActivity

### ISSUE THREAD

**Issue by SB2318** [DSC-PHCET/gdsc-android-app#69]
### Here you have to done two task.
1. Set a custom theme for TrackDetailActivity in the AndroidManifest.xml file.
2. Change the app bar color(but do not change anything in the themes.xml file).

![problem_final](https://user-images.githubusercontent.com/87614560/163174464-2f714402-35bc-4c3e-8e8b-0a52bdc343cc.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by sdcode001** [comment]
@SB2318 as I have finished previous issue so I want to work on this issue.please assign it yo me

**Comment by SB2318** [comment]
Okay, If you have any doubt regarding this issue, contact us on discord.

**Comment by SB2318** [comment]
@sdcode001 now, you can start your work. Mind it others contributors are waiting. 😇👍

**Comment by SB2318** [comment]
### If anyone wants to work on this issue, go ahead. But try to understand the problem first. Otherwise PR will not be accepted.

**Comment by sdcode001** [comment]
@SB2318 i am very close to the solution. please re assign it to me.

**Comment by sdcode001** [comment]
please check the PR
