### ISSUE TITLE
docs: Add Issue Templates

### ISSUE THREAD

**Issue by maityamit** [DSC-PHCET/gdsc-android-app#7]
Changes
Adding Issue templates
Template path ``` .github/ISSUE_TEMPLATE ```

![156198784-b2e8d551-3df4-4aff-a7c7-051a88c344c0](https://user-images.githubusercontent.com/74618071/156573614-4c5ee648-acc1-47b4-94ed-72a9357b791b.png)

![156169861-53b91128-a1aa-4751-805e-affb8a4924a3](https://user-images.githubusercontent.com/74618071/156573621-9900c761-1996-4034-b344-e010ac6ad4e2.png)

Contribution towards GSsoc`22, Thank you

- [x] Code of conduct.

**Comment by maityamit** [comment]
I want to work this issue under GSSoC'22. 👋
Please assign me.

**Comment by fin1te** [comment]
> I want to work this issue under GSSoC'22. 👋 Please assign me.

Assigned it to you, good luck! just make the changes on a new branch
