### ISSUE TITLE
Feature: Enable up navigation in TrackDetailActivity

### ISSUE THREAD

**Issue by SB2318** [DSC-PHCET/gdsc-android-app#70]
### Feature description

https://user-images.githubusercontent.com/87614560/162071482-7548c75e-dcf7-441a-af4b-4f17f5d1a192.mp4

🗝️ Point: 
1. **You have a knowledge on navigation**
2. **You know how to add up button without using parent activity concept** 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by SB2318** [comment]
Start work on this issue after successful merge of issue #69

**Comment by MohitGupta121** [comment]
I want to work on this issue please assign me

**Comment by MohitGupta121** [comment]
Thanks you

**Comment by SB2318** [comment]
> Start work on this issue after successful merge of issue #69

@MohitGupta121

**Comment by SB2318** [comment]
Am sorry @MohitGupta121 for the delay.  
But previous work is necessary.

**Comment by MohitGupta121** [comment]
> Am sorry @MohitGupta121 for the delay. But previous work is necessary.

It's Ok no problem I'm waiting

**Comment by MohitGupta121** [comment]
@fin1te  can now I'll raise PR for that issue
